[package]
name = "platform"
version = "0.0.1"
authors = ["Chris Williams <diosix@tuta.io>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies.devicetree]
path = "../devicetree"

[dependencies.qemuprint]
path = "../qemuprint"
